ServerRoot "/usr/local/apache2"
Listen 80
ServerName www.cliente2.br

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule headers_module modules/mod_headers.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module   modules/mod_authz_core.so
LoadModule authz_host_module   modules/mod_authz_host.so

User daemon
Group daemon
ProxyPreserveHost On

# ================================
# Conteúdo estático
# ================================
<VirtualHost *:80>
    ServerName www.cliente2.br
    ServerAlias cliente2.br
    DocumentRoot "/var/www/static"

    <Directory "/var/www/static">
        Options -Indexes +FollowSymLinks
        Require all granted
    </Directory>
    DirectoryIndex index.html
</VirtualHost>

# ================================
# WordPress
# ================================
<VirtualHost *:80>
    ServerName wordpress.cliente2.br

    ProxyPass        / http://wordpress/
    ProxyPassReverse / http://wordpress/

    <Location />
        RequestHeader set X-Real-IP        "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-For  "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-Proto "http"
    </Location>
</VirtualHost>

# ================================
# Adminer
# ================================
<VirtualHost *:80>
    ServerName adminer.cliente2.br

    ProxyPass        / http://adminer:8080/
    ProxyPassReverse / http://adminer:8080/

    <Location />
        RequestHeader set X-Real-IP        "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-For  "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-Proto "http"
    </Location>
</VirtualHost>

# ================================
# Portal
# ================================
<VirtualHost *:80>
    ServerName portal.cliente2.br

    ProxyPass        / http://portal_apache/
    ProxyPassReverse / http://portal_apache/

    <Location />
        RequestHeader set X-Real-IP        "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-For  "%{REMOTE_ADDR}e"
        RequestHeader set X-Forwarded-Proto "http"
    </Location>
</VirtualHost>

