version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    container_name: cliente1-traefik
    restart: always
    ports:
      - "8880:80"
      - "8843:443"
      - "8088:8080"
    networks:
      - interna
      - externa
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock  
      - ./certs:/certs

  nginx-sangue:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-sangue
    restart: always
    networks:
      - interna
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sangue.rule=Host(`sangue.cliente.br`)"
      - "traefik.http.routers.sangue.entrypoints=websecure"
      - "traefik.http.routers.sangue.tls=true"
      - "traefik.http.services.sangue.loadbalancer.server.port=80"

networks:
  interna:
    driver: bridge
  externa:
    external: true
