version: '3.3'

services: 
  wordpress:
    build: ./wordpress
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes: 
      - ./wordpress:/var/www/html/wp-content/plugins/meu-plugin
    networks:
      interna:
        aliases:
          - wordpress.cliente2.br

  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: 
      - db:/var/lib/mysql
    networks:
      - interna

  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    networks:
      interna:
        aliases:
          - adminer.cliente2.br

  portal_apache:
    build:
      context: ./portal_apache
      dockerfile: Dockerfile
    container_name: portal_apache
    networks:
      - interna

  apache_proxy:
    image: httpd:latest
    container_name: apache_proxy
    depends_on:
      - wordpress
      - portal_apache
      - adminer
    networks:
      - interna
      - externa
    volumes:
      - ./apache_proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache_proxy/static:/var/www/static

networks:
  interna: 
    driver: bridge
  externa:
    external: true

volumes: 
  db: